name: NachoSpigot Build

on: []

jobs:
  build:
    runs-on: ubuntu-latest
    if: "!contains(github.event.head_commit.message, '[skip]')"
    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 17
      uses: actions/setup-java@v1
      with:
        java-version: 17
        server-id: github
        settings-path: ${{ github.workspace }}

    - name: Install minecraft-server to local repo
      run: |
        git submodule update --init
        ./remap.sh

    - name: Build with Maven
      run: mvn clean package --file $GITHUB_WORKSPACE/pom.xml
      
    - name: Upload Server Artifact
      uses: actions/upload-artifact@v2.2.0
      with:
        name: NachoSpigot-server
        path: ${{ github.workspace }}/NachoSpigot-Server/target/NachoSpigot.jar

    - name: Upload API Artifact
      uses: actions/upload-artifact@v2.2.0
      with:
        name: NachoSpigot-API
        path: ${{ github.workspace }}/NachoSpigot-API/target/NachoSpigot-API.jar
