name: Test PR

on:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    if: ${{ !contains(github.event.head_commit.message, '[skip]') || github.repository != github.event.pull_request.head.repo.full_name}}
    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 15
      uses: actions/setup-java@v1
      with:
        java-version: 15
        server-id: github
        settings-path: ${{ github.workspace }}
    - name: Install minecraft-server to local repo
      run: |
        git submodule update --init
        ./remap.sh

    - name: Build with Maven
      run: mvn clean package --file $GITHUB_WORKSPACE/pom.xml
